apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-premium
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
